apiVersion: v2
name: toolhive-registry-server
description: A Helm chart for deploying the ToolHive Registry Server - the central metadata hub for enterprise MCP governance and discovery
type: application
version: 0.5.1
appVersion: 0.5.1
keywords:
  - mcp
  - registry
  - toolhive
  - model-context-protocol
home: https://github.com/stacklok/toolhive-registry-server
sources:
  - https://github.com/stacklok/toolhive-registry-server
