---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: toolhive-registry-server-manager-role
  labels:
    {{- include "toolhive-registry-server.labels" . | nindent 4 }}
rules:
- apiGroups:
  - toolhive.stacklok.dev
  resources:
  - mcpservers
  - mcpremoteproxies
  - virtualmcpservers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - services
  verbs:
  - get
  - list
  - watch
