---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "toolhive-registry-server.leaderElectionRoleName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "toolhive-registry-server.labels" . | nindent 4 }}
rules:
  {{- toYaml .Values.leaderElectionRole.rules | nindent 2 }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "toolhive-registry-server.leaderElectionRoleBindingName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "toolhive-registry-server.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "toolhive-registry-server.leaderElectionRoleName" . }}
subjects:
- kind: ServiceAccount
  name: {{ include "toolhive-registry-server.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
