name: Tests

on:
  workflow_call:

permissions:
  contents: read

jobs:
  test-go-code:
    name: Test Go Code
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5

      - name: Set up Go
        uses: actions/setup-go@44694675825211faa026b3c33043df3e48a5fa00 # v6
        with:
          go-version-file: 'go.mod'
          cache: true

      - name: Set up gotestfmt
        uses: gotesttools/gotestfmt-action@v2
        with:
          # avoid rate limiting
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install Task
        uses: arduino/setup-task@v2
        with:
          version: 3.44.1
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Run tests with coverage
        run: task registry-test
        # TODO: Uncomment this when coverage is implemented
        # run: task registry-test-coverage
        
      # TODO: Uncomment this when coverage is implemented
      # - name: Upload coverage reports to Codecov with GitHub Action
      #   uses: codecov/codecov-action@v5
      #   with:
      #     token: ${{ secrets.CODECOV_TOKEN }}
      #     slug: stacklok/toolhive

      # - name: Upload coverage to Coveralls
      #   uses: coverallsapp/github-action@v2
      #   with:
      #     file: coverage/coverage.out
