name: Docgen

on:
  workflow_call:

jobs:
  verify-swagger-docs:
    name: Verify Swagger Documentation
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5
      - name: Install Task
        uses: arduino/setup-task@v2
        with:
          version: 3.44.1
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/setup-go@44694675825211faa026b3c33043df3e48a5fa00 # v6
        with:
          go-version-file: go.mod
      - name: Install swag
        run: task install-swagger
      - run: ./cmd/help/verify.sh
