name: Docgen

on:
  workflow_call:

jobs:
  verify-swagger-docs:
    name: Verify Swagger Documentation
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6
      - name: Install Task
        uses: arduino/setup-task@v2
        with:
          version: 3.44.1
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/setup-go@7a3fe6cf4cb3a834922a1244abfce67bcef6a0c5 # v6
        with:
          go-version-file: go.mod
      - name: Install swag
        run: task install-swagger
      - run: ./cmd/help/verify.sh
